"""
Chat Routes — Live SSE Token Streaming with LangGraph

Concepts for your learning:
1. Server-Sent Events (SSE): Instead of waiting 5-10 seconds for the whole answer,
   FastAPI streams each token chunk as it is generated by Gemini.
2. graph.astream_events(version="v2"): LangGraph streams events in real-time.
   We filter for "on_chat_model_stream" to capture only LLM text tokens.
3. Database Persistence: Every prompt and Sensei response is saved to SQLite.
"""
import json
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from langchain_core.messages import HumanMessage, AIMessage

from app.core.database import get_db, SessionLocal
from app.api.deps import get_current_user
from app.models.db_models import User, Project, Chapter, Conversation, Message
from app.models.schemas import ChatStreamRequest, MessageOut
from app.core.guardrails import check_budget, BudgetError
from app.agents.graph import study_graph

router = APIRouter()


@router.get("/history/{project_id}", response_model=List[MessageOut])
def get_chat_history(
    project_id: int,
    chapter_id: Optional[int] = Query(None),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Fetches all past messages for a study project or specific chapter."""
    project = db.query(Project).filter(
        Project.id == project_id,
        Project.user_id == current_user.id
    ).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    query = db.query(Conversation).filter(Conversation.project_id == project_id)
    if chapter_id is not None:
        query = query.filter(Conversation.chapter_id == chapter_id)
    else:
        query = query.filter(Conversation.chapter_id.is_(None))

    conversation = query.first()

    # Smart history migration fallback:
    # If the user requested Chapter 1 and no conversation exists for it,
    # check if an unassigned conversation (chapter_id IS NULL) exists and migrate it!
    if not conversation and chapter_id is not None:
        first_chapter = (
            db.query(Chapter)
            .filter(Chapter.project_id == project_id)
            .order_by(Chapter.order_num.asc())
            .first()
        )
        if first_chapter and first_chapter.id == chapter_id:
            unassigned = (
                db.query(Conversation)
                .filter(Conversation.project_id == project_id, Conversation.chapter_id.is_(None))
                .first()
            )
            if unassigned:
                unassigned.chapter_id = chapter_id
                db.commit()
                db.refresh(unassigned)
                conversation = unassigned

    if not conversation:
        return []

    return conversation.messages


@router.post("/stream")
async def stream_chat(
    request: ChatStreamRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Streams Sensei's teaching responses word-by-word via SSE (Server-Sent Events).
    Automatically synthesizes a calibrated syllabus upon receiving the first chat if none exists.
    """
    # 1. Cost & Safety Guardrails Check
    try:
        await check_budget(current_user.id, db)
    except BudgetError as e:
        raise HTTPException(status_code=status.HTTP_429_TOO_MANY_REQUESTS, detail=str(e))

    # 2. Verify project ownership
    project = db.query(Project).filter(
        Project.id == request.project_id,
        Project.user_id == current_user.id
    ).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    # 3. Auto-generate syllabus on first chat if project has NO chapters
    existing_chapter_count = db.query(Chapter).filter(Chapter.project_id == request.project_id).count()
    generated_chapters_payload = None

    effective_chapter_id = request.chapter_id
    effective_difficulty = request.difficulty_level or project.difficulty_level or "beginner"

    if existing_chapter_count == 0:
        from app.agents.tools.chapters import generate_chapters_for_project, clean_chapter_title
        if request.difficulty_level:
            project.difficulty_level = request.difficulty_level
            db.commit()

        curriculum = await generate_chapters_for_project(
            topic_title=project.title,
            topic_description=f"{project.description}. User starting prompt: {request.message}",
            theme=request.theme or current_user.theme or "anime",
            difficulty_level=effective_difficulty
        )

        core_titles = [clean_chapter_title(t) for t in curriculum.get("core_chapters", []) if clean_chapter_title(t)]
        optional_titles = [clean_chapter_title(t) for t in curriculum.get("optional_chapters", []) if clean_chapter_title(t)]

        created_chapters = []
        for idx, title in enumerate(core_titles, start=1):
            chap = Chapter(
                project_id=request.project_id,
                title=title,
                order_num=idx,
                ai_generated=True
            )
            db.add(chap)
            created_chapters.append(chap)
        db.commit()

        for c in created_chapters:
            db.refresh(c)

        if created_chapters:
            effective_chapter_id = created_chapters[0].id
            from app.api.routes.projects import migrate_unassigned_conversations_to_chapter
            migrate_unassigned_conversations_to_chapter(request.project_id, effective_chapter_id, db)

            generated_chapters_payload = {
                "core_chapters": [
                    {
                        "id": c.id,
                        "title": c.title,
                        "order_num": c.order_num,
                        "progress": c.progress,
                        "status": c.status,
                        "ai_generated": c.ai_generated
                    }
                    for c in created_chapters
                ],
                "optional_chapters": optional_titles,
                "selected_chapter_id": effective_chapter_id
            }

    # 4. Fetch or initialize chapter-specific conversation record
    conv_query = db.query(Conversation).filter(
        Conversation.project_id == request.project_id
    )
    if effective_chapter_id is not None:
        conv_query = conv_query.filter(Conversation.chapter_id == effective_chapter_id)
    else:
        conv_query = conv_query.filter(Conversation.chapter_id.is_(None))

    conversation = conv_query.first()
    if not conversation:
        conversation = Conversation(
            project_id=request.project_id,
            chapter_id=effective_chapter_id,
            mood=request.mood
        )
        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    # 5. Save user message to database
    user_msg_db = Message(
        conversation_id=conversation.id,
        role="user",
        content=request.message,
        token_count=len(request.message.split())
    )
    db.add(user_msg_db)
    db.commit()

    # 6. Retrieve last 10 messages for conversational context
    past_messages = (
        db.query(Message)
        .filter(Message.conversation_id == conversation.id)
        .order_by(Message.created_at.desc())
        .limit(10)
        .all()
    )
    past_messages.reverse()

    # Format into LangChain message objects
    formatted_messages = []
    for m in past_messages:
        if m.role == "user":
            formatted_messages.append(HumanMessage(content=m.content))
        else:
            formatted_messages.append(AIMessage(content=m.content))

    # Resolve chapter title if available
    chapter_title = "General"
    if effective_chapter_id:
        ch = db.query(Chapter).filter(Chapter.id == effective_chapter_id).first()
        if ch:
            chapter_title = ch.title

    # Extract primitive values before the DB session closes
    user_id = current_user.id
    user_theme = current_user.theme or "anime"
    theme = request.theme or user_theme
    project_title = project.title
    conv_id = conversation.id

    study_mode = request.study_mode or "chill"

    async def event_generator():
        """SSE Generator that streams tokens and tool events directly from LangGraph."""
        full_ai_content = []
        thread_id = (
            f"user-{user_id}-proj-{request.project_id}-chap-{effective_chapter_id}"
            if effective_chapter_id
            else f"user-{user_id}-proj-{request.project_id}-general"
        )
        config = {"configurable": {"thread_id": thread_id}}

        graph_input = {
            "messages": formatted_messages,
            "current_topic": project_title,
            "current_chapter": chapter_title,
            "mood": request.mood,
            "theme": theme,
            "study_mode": study_mode,
            "difficulty_level": effective_difficulty,
            "target_agent": request.target_agent
        }

        current_agent_type = "sensei"

        try:
            # If syllabus was just auto-generated, broadcast it to the client immediately!
            if generated_chapters_payload:
                yield f"data: {json.dumps({'type': 'syllabus_generated', **generated_chapters_payload})}\n\n"
                first_ch_title = generated_chapters_payload['core_chapters'][0]['title']
                yield f"data: {json.dumps({'type': 'step', 'step': f'Syllabus ready! Activated Chapter 1: {first_ch_title}'})}\n\n"
            else:
                yield f"data: {json.dumps({'type': 'step', 'step': 'Analyzing your question & study context...'})}\n\n"

            # Stream tokens and tool calling events from LangGraph
            async for event in study_graph.astream_events(graph_input, config=config, version="v2"):
                kind = event["event"]

                # Detect active agent node (sensei, challenger, hype)
                if kind == "on_chain_start" and event.get("name") in ["sensei", "challenger", "hype"]:
                    current_agent_type = event["name"]
                    yield f"data: {json.dumps({'type': 'agent_switch', 'agent': current_agent_type})}\n\n"

                # 1. Tool execution started (e.g. DuckDuckGo search)
                elif kind == "on_tool_start":
                    tool_name = event.get("name", "tool")
                    raw_input = event.get("data", {}).get("input", {})
                    query = raw_input.get("query", "") if isinstance(raw_input, dict) else str(raw_input)
                    payload = {
                        "type": "tool_start",
                        "tool": tool_name,
                        "query": query
                    }
                    yield f"data: {json.dumps(payload)}\n\n"

                # 2. Tool execution finished
                elif kind == "on_tool_end":
                    tool_name = event.get("name", "tool")
                    payload = {
                        "type": "tool_end",
                        "tool": tool_name
                    }
                    yield f"data: {json.dumps(payload)}\n\n"

                # 3. Model token streaming
                elif kind == "on_chat_model_stream":
                    chunk = event["data"]["chunk"].content
                    if isinstance(chunk, str) and chunk:
                        full_ai_content.append(chunk)
                        data = json.dumps({"type": "token", "content": chunk})
                        yield f"data: {data}\n\n"

            # Stream finished — save the complete AI answer to database in a new DB session
            complete_text = "".join(full_ai_content)
            save_db = SessionLocal()
            try:
                # Approximate tokens: ~4 chars per token (standard LLM rule of thumb)
                out_tokens = max(1, len(complete_text) // 4)
                in_tokens = max(1, sum(len(m.content) // 4 for m in formatted_messages) + 350)

                ai_msg_db = Message(
                    conversation_id=conv_id,
                    role=current_agent_type,
                    content=complete_text,
                    token_count=out_tokens
                )
                save_db.add(ai_msg_db)
                save_db.commit()

                # Track exact tokens in TokenUsage table for admin metrics & guardrails
                from app.core.guardrails import record_token_usage
                record_token_usage(user_id, in_tokens, out_tokens, save_db)
            finally:
                save_db.close()

            # Emit final completion event
            yield f"data: {json.dumps({'type': 'done'})}\n\n"

        except Exception as e:
            error_data = json.dumps({"type": "error", "content": str(e)})
            yield f"data: {error_data}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream"
    )

